services:
  arctos-gui:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    ports:
      - "8080:8080"
      - "7000:7000"
    container_name: arctos-gui-python
    restart: unless-stopped
    # Map all possible CANable devices and required system devices
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"  # CANable device (primary)
      - "/dev/ttyACM1:/dev/ttyACM1"  # Additional CANable device
      - "/dev/ttyUSB0:/dev/ttyUSB0"   # Alternative device path
      - "/dev/bus/usb:/dev/bus/usb"   # USB bus access
    # Required for CAN interface setup
    # sysctls:
    #   - net.core.rmem_max=262144
    #   - net.core.wmem_max=262144
    # Required volumes for device access
    volumes:
      - /run/udev:/run/udev:ro        # For udev rules
      - /dev:/dev:rwm                 # Full device access
    # Environment variables
    environment:
      - PYTHONUNBUFFERED=1
    # Required privileges for CAN interface setup
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_RAWIO
      - SYS_ADMIN
      - SYS_MODULE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    # Network settings
    network_mode: host  # Required for raw CAN socket access
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Ensure the container has proper permissions
    user: root
    # Add necessary kernel modules
    tmpfs:
      - /run
      - /run/lock
      - /tmp
