servo_0:
  current: 1600
  direction: CW
  enable_homing: Enable
  endstop_enabled: true
  endstop_level: Low
  holding: FIFTHTY_PERCENT
  home_direction: CCW
  home_speed: 60
  microsteps: 16
  work_mode: SrvFoc

servo_1:
  current: 1600
  direction: CW
  enable_homing: Enable
  endstop_enabled: true
  endstop_level: Low
  holding: FIFTHTY_PERCENT
  home_direction: CCW
  home_speed: 60
  microsteps: 16
  work_mode: SrvFoc

servo_2:
  current: 1600
  direction: CW
  enable_homing: Enable
  endstop_enabled: true
  endstop_level: Low
  holding: FIFTHTY_PERCENT
  home_direction: CCW
  home_speed: 60
  microsteps: 16
  work_mode: SrvFoc

servo_3:
  current: 1600
  direction: CW
  enable_homing: Enable
  endstop_enabled: true
  endstop_level: Low
  holding: FIFTHTY_PERCENT
  home_direction: CCW
  home_speed: 60
  microsteps: 16
  work_mode: SrvFoc

servo_4:
  current: 1600
  direction: CW
  enable_homing: Enable
  endstop_enabled: true
  endstop_level: Low
  holding: FIFTHTY_PERCENT
  home_direction: CCW
  home_speed: 60
  microsteps: 16
  work_mode: SrvFoc

servo_5:
  current: 1600
  direction: CW
  enable_homing: Enable
  endstop_enabled: true
  endstop_level: Low
  holding: FIFTHTY_PERCENT
  home_direction: CCW
  home_speed: 60
  microsteps: 16
  work_mode: SrvFoc

