auto_update_saved_poses: false
enable_live_joint_updates: false
joint_directions:
  0: 1
  1: -1
  2: -1
  3: 1
  4: -1
  5: 1
language: English
max_fps: 30
speed_scale: 1.0
theme: Light
ui_color_theme: Blue
