auto_update_saved_poses: false
coupled_axis_mode: false
enable_live_joint_updates: false
gear_ratios:
- 13.5
- 150
- 150
- 48
- 33.0
- 10.0
homing_offsets:
  0: -103445.0
  1: -333983
  5: -78401
joint_accelerations:
  0: 200
  1: 190
  2: 190
  3: 190
  4: 190
  5: 190
joint_directions:
  0: 1
  1: -1
  2: -1
  3: 1
  4: -1
  5: 1
joint_speeds:
  0: 50
  1: 500
  2: 500
  3: 500
  4: 510
  5: 500
keyboard_send_to_robot: false
language: English
max_fps: 30
speed_scale: 1.0
theme: Light
ui_color_theme: Blue
