auto_update_saved_poses: false
coupled_axis_mode: false
enable_live_joint_updates: false
gear_ratios:
- 13.5
- 150
- 150
- 48
- 33.0
- 10.0
homing_offsets:
  0: -103445.0
  1: -333983
  2: -237969
  3: 180477
  4: 115507
  5: -78401
joint_accelerations:
  0: 240
  1: 240
  2: 240
  3: 240
  4: 240
  5: 240
joint_directions:
  0: 1
  1: -1
  2: -1
  3: -1
  4: -1
  5: -1
joint_speeds:
  0: 800
  1: 800
  2: 800
  3: 800
  4: 1000
  5: 800
keyboard_send_to_robot: true
language: English
max_fps: 30
speed_scale: 1.0
theme: Light
ui_color_theme: Blue
