auto_update_saved_poses: false
coupled_axis_mode: false
enable_live_joint_updates: true
gear_ratios:
- 13.5
- 150
- 150
- 48
- 27.3375
- 10.0
homing_offsets:
  0: -98018
  1: -352531
  2: -244011
  3: 178965.0
  4: 121972
  5: -79420
joint_accelerations:
  0: 150
  1: 230
  2: 230
  3: 200
  4: 200
  5: 200
joint_directions:
  0: 1
  1: -1
  2: -1
  3: -1
  4: -1
  5: -1
joint_speeds:
  0: 500
  1: 3000
  2: 3000
  3: 1500
  4: 1000
  5: 800
keyboard_send_to_robot: false
language: English
max_fps: 30
speed_scale: 0.1
theme: Light
ui_color_theme: Blue
